#!/usr/bin/python

import sys
import os
import tempfile
import shutil
import subprocess
import uuid
import dicom

def new_uid(old_uid):
    """create a new DICOM UID

    return an already-created UID if the old UID has already been replaced
    """
    if old_uid not in uids:
        uids[old_uid] = '2.25.%d' % uuid.uuid1().int
    return uids[old_uid]

progname = os.path.basename(sys.argv[0])
uids = {}

if len(sys.argv) != 5:
    print 'usage:%s dir user subject session' % progname
    sys.exit(1)

(dir, user, subject, session) = sys.argv[1:]

staged_files = []

tempdir = tempfile.mkdtemp()
try:
    i = 0
    for (dirpath, dirnames, filenames) in os.walk(dir):
        for fname in filenames:
            ffname = '%s/%s' % (dirpath, fname)
            print ffname
            try:
                do = dicom.read_file(ffname)
            except:
                continue
            do.StudyComments = 'incf:%s' % user
            do.PatientsName = subject
            do.PatientID = session
            for name in ('SOPInstanceUID', 
                         'StudyInstanceUID', 
                         'SeriesInstanceUID', 
                         'booyah', 
                         'FrameofReferenceUID'):
                try:
                    el = do.data_element(name)
                except KeyError:
                    pass
                else:
                    if el is not None:
                        do.data_element(name).value = new_uid(el.value)
# del do[0xgp, 0xel] not working for me
#                del do.PerformingPhysiciansName
#                tag = do.data_element('PerformingPhysiciansName').tag
#                del do[tag]
            out_fname = '%s/%08d' % (tempdir, i)
            i += 1
            dicom.write_file(out_fname, do)
            staged_files.append(out_fname)
            print '    %s' % out_fname
    args = ['storescu', '-v', '-aec', 'XNAT', 'xnat.incf.org', '104']
    args.extend(staged_files)
    subprocess.call(args)
finally:
    shutil.rmtree(tempdir)

sys.exit(0)

# eof
