#!/usr/bin/python

import sys
import os
import tempfile
import shutil
import subprocess
import uuid
import dicom

deident_tags = [(0x0008, 0x0090), # Referring Physician's Name
                (0x0008, 0x0096), # Referring Physician Identification
                (0x0008, 0x1048), # Physician(s) of Record
                (0x0008, 0x1049), # Physician(s) of Record Identification
                (0x0008, 0x1050), # Performing Physicians' Name
                (0x0008, 0x1052), # Performing Physician Identification
                (0x0008, 0x1060), # Name of Physician(s) Reading Study
                (0x0008, 0x1062), # Physician(s) Reading Study Identification
               ]

# del dicom_object[(xxxx, yyyy)] doesn't work for me, but del dicom_object[tag] does, where tag = dicom.tag.Tag((xxxx, yyyy))
deident_tags = [ dicom.tag.Tag(tag) for tag in deident_tags ]

def new_uid(old_uid):
    """create a new DICOM UID

    return an already-created UID if the old UID has already been replaced
    """
    if old_uid not in uids:
        uids[old_uid] = '2.25.%d' % uuid.uuid1().int
    return uids[old_uid]

progname = os.path.basename(sys.argv[0])
uids = {}

if len(sys.argv) != 5:
    print 'usage:%s dir user subject session' % progname
    sys.exit(1)

(dir, user, subject, session) = sys.argv[1:]

staged_files = []

tempdir = tempfile.mkdtemp()
try:
    i = 0
    for (dirpath, dirnames, filenames) in os.walk(dir):
        for fname in filenames:
            ffname = '%s/%s' % (dirpath, fname)
            print ffname
            try:
                do = dicom.read_file(ffname)
            except:
                continue
            do.StudyComments = 'incf:%s' % user
            do.PatientsName = subject
            do.PatientID = session
            for name in ('SOPInstanceUID', 
                         'StudyInstanceUID', 
                         'SeriesInstanceUID', 
                         'booyah', 
                         'FrameofReferenceUID'):
                try:
                    el = do.data_element(name)
                except KeyError:
                    pass
                else:
                    if el is not None:
                        do.data_element(name).value = new_uid(el.value)
                    for tag in deident_tags:
                        if tag in do:
                            del do[tag]
            out_fname = '%s/%08d' % (tempdir, i)
            i += 1
            dicom.write_file(out_fname, do)
            staged_files.append(out_fname)
            print '    %s' % out_fname
    args = ['storescu', '-v', '-aec', 'XNAT', 'xnat.incf.org', '104']
    args.extend(staged_files)
    subprocess.call(args)
finally:
    shutil.rmtree(tempdir)

sys.exit(0)

# eof
