#!/usr/bin/python

# See file COPYING distributed with the one_click package for the copyright
# and license.

# TODO: server configuration

import sys
import os
import tempfile
import shutil
import string
import uuid
import csv
import subprocess
import StringIO
from PyQt4 import QtCore, QtGui, uic
import httplib2
import dicom

#############################################################################
# defaults and definitions
#

try:
    subprocess.call(['storescu'], 
                    stdout=subprocess.PIPE, 
                    stderr=subprocess.PIPE)
except:
    have_storescu = False
else:
    have_storescu = True

#TODO remove
# projects[identifier] -> have permission to upload
projects = {'christian': True, 
            'rembrandt': False}

conf_url = 'http://xnat.incf.org/conf.txt'

files_per_push = 5

# our cache of new UIDs: uids[old UID] -> new UID
uids = {}

deident_tags = [(0x0008, 0x0050), # Accession Number
                (0x0008, 0x0080), # InstitutionName
                (0x0008, 0x0090), # Referring Physician's Name
                (0x0008, 0x0096), # Referring Physician Identification
                (0x0008, 0x1048), # Physician(s) of Record
                (0x0008, 0x1049), # Physician(s) of Record Identification
                (0x0008, 0x1050), # Performing Physicians' Name
                (0x0008, 0x1052), # Performing Physician Identification
                (0x0008, 0x1060), # Name of Physician(s) Reading Study
                (0x0008, 0x1062), # Physician(s) Reading Study Identification
                (0x0010, 0x0030), # Patient's Birth Date
                (0x0010, 0x0050), # Patient's Insurance Plan Code SQ
                (0x0010, 0x0101), # Patient's Primary Language Code SQ
                (0x0010, 0x1000), # Other Patient IDs
                (0x0010, 0x1001), # Other Patient Names
                (0x0010, 0x1002), # Other Patient IDs SQ
                (0x0010, 0x1005), # Patient's Birth Name
                (0x0010, 0x1010), # Patient's Age
                (0x0010, 0x1040), # Patient's Address
                (0x0010, 0x1060), # Patient's Mother's Birth Name
               ]

# del dicom_object[(xxxx, yyyy)] doesn't work for me, but
# del dicom_object[tag] does, where tag = dicom.tag.Tag((xxxx, yyyy))
deident_tags = [ dicom.tag.Tag(tag) for tag in deident_tags ]

# comments on performed procedure
# if present, this can mess up the project change in the prearchive
copp_tag = dicom.tag.Tag((0x0040, 0x0280))

completion_msg = """Your upload is complete.  QC will be run on your data and you will be notified by e-mail when the QC reports are ready."""

server_config_msg = 'There was an error reading server configuration.  Please contact xnat-admin@incf.org for assistance.'

no_dcmtk_msg = """storescu (the program used to send data to the server) was not found on your system.  Please install DCMTK (or adjust your path) before proceeding."""

bad_protocol_msg = """The INCF server does not support the protocol used in this program.  Please update this program (updates are available at xnat.incf.org)."""

#############################################################################
# classes
#

class InvalidDicomError(Exception):
    """Exception raised when read_dicom_file() tries to read a file that 
    doesn't have DICM at byte 128.
    """

class XNAT:

    def __init__(self, base_url, user_name, password):
        self.base_url = base_url
        h = httplib2.Http()
        h.add_credentials(user_name, password)
        url = '%s/data/JSESSION' % self.base_url
        (response, content) = h.request(url)
        if response['status'] != '200':
            raise ValueError
        if 'set-cookie' not in response:
            raise ValueError
        self.jsession_cookie = response['set-cookie'].split(';')[0]
        self.user_name = user_name
        self._projects = None
        self._user_projects = None
        self._subjects = {}
        self._sessions = {}
        return

    def _request(self, url, method='GET', expected_status='200'):
        full_url = '%s/data%s' % (self.base_url, url)
        h = httplib2.Http()
        headers = {'Cookie': self.jsession_cookie}
        (response, content) = h.request(full_url, method, headers=headers)
        if response['status'] != expected_status:
            raise RequestError(method, full_url, response['status'])
        return (response, content)

    def _request_table(self, url):
        (response, content) = self._request('%s?format=csv' % url)
        reader = csv.reader(StringIO.StringIO(content))
        header = reader.next()
        return [ dict(zip(header, row)) for row in reader ]

    def close(self):
        self._request('/JSESSION', 'DELETE')
        return

    def projects(self):
        if self._projects is None:
            self._projects = []
            for project in self._request_table('/projects'):
                self._projects.append(project['ID'])
        return self._projects

    def user_projects(self):
        if self._user_projects is None:
            self._user_projects = []
            for project in self.projects():
                user_url = '/projects/%s/users' % project
                for user in self._request_table(user_url):
                    if user['login'] == self.user_name:
                        self._user_projects.append(project)
                        break
        return self._user_projects

    def create_project(self, project):
        if project in self.projects():
            raise ValueError('project %s exists' % project)
        self._request('/projects/%s' % project, 'PUT', '200')
        # reset the cache
        self._projects = None
        self._user_projects = None
        return

    def subjects(self, project):
        if project not in self.projects():
            raise ValueError('project %s not found' % project)
        if project not in self._subjects:
            self._subjects[project] = []
            url = '/projects/%s/subjects' % project
            for subject in self._request_table(url):
                self._subjects[project].append(subject['label'])
            self._subjects[project].sort()
        return self._subjects[project]

    def create_subject(self, project, subject):
        if project not in self.projects():
            raise ValueError('project %s not found' % project)
        if subject in self.subjects(project):
            raise ValueError('subject %s exists in project %s' % (subject, 
                                                                  project))
        self._request('/projects/%s/subjects/%s' % (project, subject), 
                      'PUT', 
                      '201')
        # reset the cache -- this will exist due to our self.subjects(project) 
        # call above
        del self._subjects[project]
        return

    def sessions(self, project):
        if project not in self._sessions:
            self._sessions[project] = {}
        sessions = []
        for subject in self.subjects(project):
            if subject not in self._sessions[project]:
                self._sessions[project][subject] = []
                url = '/projects/%s/subjects/%s/experiments' % (project, 
                                                                subject)
                for session in self._request_table(url):
                    self._sessions[project][subject].append(session['label'])
            sessions.extend(self._sessions[project][subject])
        sessions.sort()
        return sessions

    def create_session(self, project, subject, session):
        if project not in self.projects():
            raise ValueError('project %s not found' % project)
        if subject not in self.subjects(project):
            raise ValueError('no subject %s in project %s' % (subject, project))
        if session in self.sessions(project):
            raise ValueError('session %s exists in project %s' % (session, 
                                                                  project))
        fmt = '/projects/%s/subjects/%s/experiments/%s?xsiType=mrSessionData'
        url = fmt % (project, subject, session)
        self._request(url, 'PUT', '201')
        # reset the cache -- this will exist due to the calls above
        del self._sessions[project][subject]
        return

#############################################################################
# functions
#

def parse_server_configuration(data):
    conf = {}
    # header -- conf version 1 is text key/value (the only thing we handle here)
    if data.split('\n')[0] != 'conf 1':
        return None
    for line in data.split('\n')[1:]:
        if not line:
            continue
        (key, value) = line.split(' ', 1)
        if key == 'client_protocol':
            conf.setdefault(key, []).append(value)
        elif key in ('xnat_base', 'push_target'):
            conf[key] = value
        else:
            conf.setdefault(key, []).append(value)
    for key in ('client_protocol', 'xnat_base', 'push_target'):
        if key not in conf:
            return None
    (push_host, push_port) = conf['push_target'].split(':')
    conf['push_host'] = push_host
    conf['push_port'] = push_port
    return conf

def read_dicom_file(fname):
    """Read a DICOM file, raising an exception if the 'DICM' marker is not 
    present at byte 128.

    dicom.read_file() does this as of pydicom 0.9.5.
    """
    fo = open(fname)
    try:
        preamble = fo.read(128)
        magic = fo.read(4)
        if len(preamble) != 128 or magic != 'DICM':
            raise InvalidDicomError
        fo.seek(0)
        do = dicom.read_file(fo)
    finally:
        fo.close()
    return do

def patient_studies(dicom_files, studies, patient_id):
    """given our dicom_files and studies records and a patient ID, return a 
    list of (datetime, study instance UID) ordered by date+time"""
    ps = []
    for uid in dicom_files[patient_id]:
        datetime = '%s%s' % studies[uid]
        ps.append([datetime, uid])
    ps.sort(lambda a, b: cmp(a[0], b[0]))
    for el in ps:
        date_time_parts = (el[0][0:4], 
                           el[0][4:6], 
                           el[0][6:8], 
                           el[0][8:10], 
                           el[0][10:12], 
                           el[0][12:14])
        el[0] = '%s-%s-%s %s:%s:%s' % date_time_parts
    return ps

def new_uid(old_uid):
    """Create a new DICOM UID.

    Return an already-created UID if the old UID has already been replaced.
    """
    if old_uid not in uids:
        uids[old_uid] = '2.25.%d' % uuid.uuid1().int
    return uids[old_uid]

#############################################################################
# GUI elements
#

class Application(QtGui.QApplication):

    def __init__(self, argv, have_storescu):
        # XNAT connection object (set by self.login_dialog)
        self.xnat = None
        # self.dicom_files[PatientID][StudyInstanceUID] -> list of file names
        # set by self.file_loader
        self.dicom_files = None
        # self.studies[StudyInstanceUID] -> (study date, study time)
        # set by self.file_loader
        self.studies = None
        # self.projects[PatientID] -> XNAT project
        # set by self.info_dialog
        self.projects = None
        # self.projects[PatientID] -> XNAT subject
        # set by self.info_dialog
        self.subjects = None
        # self.projects[StudyInstanceUID] -> XNAT session
        # set by self.info_dialog
        self.sessions = None
        QtGui.QApplication.__init__(self, argv)
        self.quit_dialog = QuitDialog(self)
        # set this to true for a clean exit if there are any startup errors
        self.pre_quit = False
        if not have_storescu:
            self.show_exit_notice(no_dcmtk_msg)
            self.pre_quit = True
        elif not self.read_config():
            self.pre_quit = True
        elif '2' not in self.server_conf['client_protocol']:
            self.show_exit_notice(bad_protocol_msg)
            self.pre_quit = True
        elif not self.scan_files():
            self.pre_quit = True
        return

    def read_config(self):
        try:
            h = httplib2.Http()
            (response, content) = h.request(conf_url)
            if response['status'] != '200':
                self.show_exit_notice(server_config_msg)
                return False
            self.server_conf = parse_server_configuration(content)
            if not self.server_conf:
                self.show_exit_notice(server_config_msg)
                return False
        except:
            self.show_exit_notice(server_config_msg)
            return False
        return True

    def scan_files(self):
        paths = self.argv()[1:]
        self.file_loader = FileLoaderDialog(self, paths)
        self.file_loader.show()
        self.file_loader.scan()
        self.file_loader.read()
        self.file_loader.hide()
        if self.file_loader.quit_called:
            return False
        elif not self.dicom_files:
            self.show_exit_notice('No dicom files found.')
            return False
        else:
            self.agreement_dialog = AgreementDialog(self)
            self.agreement_dialog.show()
        return True

    def login(self):
        self.agreement_dialog.hide()
        self.login_dialog = LoginDialog(self)
        self.login_dialog.show()
        return

    def get_upload_info(self):
        self.login_dialog.hide()
        self.info_dialog = InfoDialog(self)
        self.info_dialog.show()
        return

    def upload(self):
        self.info_dialog.hide()
        self.upload_dialog = UploadDialog(self)
        self.upload_dialog.show()
        self.upload_dialog.upload()
        if self.upload_dialog.quit_called:
            self.quit()
        return

    def finish(self):
        self.quit()

    def show_exit_notice(self, msg):
        self.exit_notice_dialog = ExitNoticeDialog(self, msg)
        self.exit_notice_dialog.exec_()
        self.quit()

class UploadDialog(QtGui.QDialog):

    def __init__(self, app):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/upload_dialog.ui', self)
        self.info_label.setText('Preparing to upload...')
        self.app = app
        self.n_files = 0
        self.n_prepped = 0
        self.n_sent = 0
        for patient_id in self.app.dicom_files:
            for study_instance_uid in self.app.dicom_files[patient_id]:
                n = len(self.app.dicom_files[patient_id][study_instance_uid])
                self.n_files += n
        self.progress.setRange(0, 2*self.n_files)
        self.progress.setValue(0)
        self.state = 'uploading'
        return

    def upload(self):
        self.quit_called = False
        for patient_id in self.app.dicom_files:
            for study_instance_uid in self.app.dicom_files[patient_id]:
                self.send_session(patient_id, study_instance_uid)
                if self.quit_called:
                    return
        self.stop_button.setText('Quit')
        self.info_label.setText(completion_msg)
        self.state = 'done'
        return

    def send_session(self, patient_id, study_instance_uid):
        project = self.app.projects[patient_id]
        subject = self.app.subjects[patient_id]
        session = self.app.sessions[study_instance_uid]
        if project not in self.app.xnat.projects():
            self.app.xnat.create_project(project)
        if subject not in self.app.xnat.subjects(project):
            self.app.xnat.create_subject(project, subject)
        if session not in self.app.xnat.sessions(project):
            self.app.xnat.create_session(project, subject, session)
        files = self.app.dicom_files[patient_id][study_instance_uid]
        prepped_files = []
        tempdir = tempfile.mkdtemp()
        try:
            for fname in files:
                msg = 'Preparing file %d of %d...' % (self.n_prepped+1, 
                                                      self.n_files)
                self.info_label.setText(msg)
                do = read_dicom_file(fname)
                study_comments = 'incf 2\n'
                study_comments += 'upload_agreement signed\n'
                study_comments += 'user %s\n' % self.app.xnat.user_name
                study_comments += 'project %s' % project
                do.StudyComments = study_comments
                do.PatientName = subject
                do.PatientID = session
                for name in ('SOPInstanceUID',
                             'StudyInstanceUID',
                             'SeriesInstanceUID',
                             'FrameOfReferenceUID'):
                    try:
                        el = do.data_element(name)
                    except KeyError:
                        pass
                    else:
                        if el is not None:
                            do.data_element(name).value = new_uid(el.value)
                for tag in deident_tags:
                    if tag in do:
                        del do[tag]
                if copp_tag in do:
                    del do[copp_tag]
                out_fname = '%s/%08d' % (tempdir, len(prepped_files))
                dicom.write_file(out_fname, do)
                prepped_files.append(out_fname)
                self.n_prepped += 1
                self.progress.setValue(self.n_prepped+self.n_sent)
                self.app.processEvents()
                if self.quit_called:
                    return
            # chunk our sends (files_per_push files per storescu call)
            while prepped_files:
                args = ['storescu', 
                        '-v', 
                        '-aec', 
                        'XNAT', 
                        self.app.server_conf['push_host'], 
                        self.app.server_conf['push_port']]
                args.extend(prepped_files[:files_per_push])
                po = subprocess.Popen(args, 
                                      stdout=subprocess.PIPE, 
                                      stderr=subprocess.STDOUT)
                # first loop while storescu is running...
                msg = 'Sending file %d of %d...' % (self.n_sent+1, self.n_files)
                self.info_label.setText(msg)
                self.progress.setValue(self.n_prepped+self.n_sent)
                self.app.processEvents()
                if self.quit_called:
                    return
                while True:
                    line = po.stdout.readline()
                    if 'Releasing Association' in line:
                        break
                    if 'Sending Store Request' in line:
                        self.n_sent += 1
                        msg = 'Sending file %d of %d...' % (self.n_sent+1, 
                                                            self.n_files)
                        self.info_label.setText(msg)
                        self.progress.setValue(self.n_prepped+self.n_sent)
                        self.app.processEvents()
                        if self.quit_called:
                            return
                    if not line:
                        break
                try:
                    po.wait()
                except OSError:
                    # ignore the errno 4 (interrupted system call) -- known bug
                    pass
                prepped_files = prepped_files[files_per_push:]
        finally:
            shutil.rmtree(tempdir)
        return

    def quit(self):
        if self.state == 'uploading':
            self.app.quit_dialog.show()
            if self.app.quit_dialog.exec_():
                self.quit_called = True
        else:
            self.app.finish()
        return

class InfoDialog(QtGui.QDialog):

    info_label_width = 50
    info_edit_width = 100
    info_status_width = 150

    def __init__(self, app):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/info_dialog.ui', self)
        self.app = app
        self.project_widgets = {}
        self.subject_widgets = {}
        self.session_widgets = {}
        for patient_id in sorted(self.app.dicom_files):
            widget = QtGui.QWidget()
            layout = QtGui.QVBoxLayout()
            widget.setLayout(layout)
            layout.addWidget(QtGui.QLabel('Patient ID %s' % patient_id))
            ps = patient_studies(self.app.dicom_files, 
                                 self.app.studies, 
                                 patient_id)
            project_widget = QtGui.QWidget()
            project_layout = QtGui.QHBoxLayout()
            project_widget.setLayout(project_layout)
            label_widget = QtGui.QLabel('Project')
            label_widget.setFixedWidth(self.info_label_width)
            project_layout.addWidget(label_widget)
            edit = QtGui.QLineEdit()
            edit.setFixedWidth(self.info_edit_width)
            self.connect(edit, 
                         QtCore.SIGNAL('textEdited(QString)'), 
                         self.validate)
            project_layout.addWidget(edit)
            status = QtGui.QLabel()
            status.setFixedWidth(self.info_status_width)
            project_layout.addWidget(status)
            layout.addWidget(project_widget)
            self.project_widgets[patient_id] = {'edit': edit, 'status': status}
            subject_widget = QtGui.QWidget()
            subject_layout = QtGui.QHBoxLayout()
            subject_widget.setLayout(subject_layout)
            label_widget = QtGui.QLabel('Subject')
            label_widget.setFixedWidth(self.info_label_width)
            subject_layout.addWidget(QtGui.QLabel('Subject'))
            edit = QtGui.QLineEdit()
            edit.setFixedWidth(self.info_edit_width)
            self.connect(edit, 
                         QtCore.SIGNAL('textEdited(QString)'), 
                         self.validate)
            subject_layout.addWidget(edit)
            status = QtGui.QLabel()
            status.setFixedWidth(self.info_status_width)
            subject_layout.addWidget(status)
            layout.addWidget(subject_widget)
            self.subject_widgets[patient_id] = {'edit': edit, 'status': status}
            session_number = 0
            for (date_time, study_instance_uid) in ps:
                session_number += 1
                text = 'Session %d: %s' % (session_number, date_time)
                layout.addWidget(QtGui.QLabel(text))
                session_widget = QtGui.QWidget()
                session_layout = QtGui.QHBoxLayout()
                session_widget.setLayout(session_layout)
                label_widget = QtGui.QLabel('Session')
                label_widget.setFixedWidth(self.info_label_width)
                session_layout.addWidget(label_widget)
                edit = QtGui.QLineEdit()
                edit.setFixedWidth(self.info_edit_width)
                self.connect(edit, 
                             QtCore.SIGNAL('textEdited(QString)'), 
                             self.validate)
                session_layout.addWidget(edit)
                status = QtGui.QLabel('status')
                status.setFixedWidth(self.info_status_width)
                session_layout.addWidget(status)
                sw = self.session_widgets.setdefault(patient_id, {})
                sw[study_instance_uid] = {'edit': edit, 'status': status}
                layout.addWidget(session_widget)
            tab = QtGui.QScrollArea()
            tab.setWidget(widget)
            self.tab_widget.addTab(tab, str(patient_id))
        # force loading of the XNAT information now (so we don't have delays 
        # later)
        self.projects = self.app.xnat.projects()
        self.user_projects = self.app.xnat.user_projects()
        self.subjects = {}
        self.sessions = {}
        for project in self.user_projects:
            self.subjects[project] = self.app.xnat.subjects(project)
            self.sessions[project] = self.app.xnat.sessions(project)
        self.validate()
        return

    def _validate_project(self, patient_id):
        valid = True
        widgets = self.project_widgets[patient_id]
        project = str(widgets['edit'].text())
        if not project:
            widgets['status'].setText('No project given')
            valid = False
        elif not self._validate_identifier(project):
            widgets['status'].setText('Bad project name')
            valid = False
        elif project in self.user_projects:
            widgets['status'].setText('Project exists')
        elif project in self.projects:
            widgets['status'].setText('Permission denied')
            valid = False
        else:
            widgets['status'].setText('New project')
        if not valid:
            self.subject_widgets[patient_id]['edit'].setEnabled(False)
            self.subject_widgets[patient_id]['status'].setText('')
        else:
            self.subject_widgets[patient_id]['edit'].setEnabled(True)
            if not self._validate_subject(patient_id, project):
                valid = False
        if not valid:
            for widgets in self.session_widgets[patient_id].itervalues():
                widgets['edit'].setEnabled(False)
                widgets['status'].setText('')
        else:
            for widgets in self.session_widgets[patient_id].itervalues():
                widgets['edit'].setEnabled(True)
            if not self._validate_sessions(patient_id, project):
                valid = False
        return valid

    def _validate_subject(self, patient_id, project):
        valid = True
        subject_widgets = self.subject_widgets[patient_id]
        subject = str(subject_widgets['edit'].text())
        if not subject:
            subject_widgets['status'].setText('No subject given')
            valid = False
        elif not self._validate_identifier(subject):
            subject_widgets['status'].setText('Bad subject name')
            valid = False
        elif project not in self.user_projects:
            subject_widgets['status'].setText('New subject')
        elif subject in self.subjects[project]:
            subject_widgets['status'].setText('Existing subject')
        else:
            subject_widgets['status'].setText('New subject')
        return valid

    def _validate_sessions(self, patient_id, project):
        valid = True
        for widgets in self.session_widgets[patient_id].itervalues():
            session = str(widgets['edit'].text())
            if not session:
                widgets['status'].setText('No session given')
                valid = False
            elif not self._validate_identifier(session):
                widgets['status'].setText('Bad session name')
                valid = False
            elif project not in self.user_projects:
                widgets['status'].setText('New session')
            elif session in self.sessions[project]:
                widgets['status'].setText('Session exists')
                valid = False
            else:
                widgets['status'].setText('New session')
        return valid

    def validate(self, string=None):
        error_patients = set()
        for patient_id in self.project_widgets:
            if not self._validate_project(patient_id):
                error_patients.add(patient_id)
        # check for duplicate session IDs
        # session_ids[project][session_id] -> list of (edit, status) widget tuples
        session_ids = {}
        # patient_ids[project] -> list of patient ids
        patient_ids = {}
        for patient_id in self.session_widgets:
            for session_widgets in self.session_widgets[patient_id].itervalues():
                if not session_widgets['edit'].isEnabled():
                    continue
                session_id = str(session_widgets['edit'].text())
                if not session_id or not self._validate_identifier(session_id):
                    continue
                project = self.project_widgets[patient_id]['edit'].text()
                patient_ids.setdefault(project, []).append(patient_id)
                d = session_ids.setdefault(project, {})
                d.setdefault(session_id, []).append(session_widgets)
        for project in session_ids:
            for session_id in session_ids[project]:
                widget_list = session_ids[project][session_id]
                if len(widget_list) > 1:
                    for widgets in widget_list:
                        widgets['status'].setText('duplicate')
                    for patient_id in patient_ids[project]:
                        error_patients.add(patient_id)
        if not error_patients:
            self.error_label.setText('')
            self.upload_button.setEnabled(True)
        else:
            # find the first project with an error
            patient_id = sorted(error_patients)[0]
            self.error_label.setText('Error in %s.' % patient_id)
            self.upload_button.setEnabled(False)
        return

    def _validate_identifier(self, identifier):
        """Check if a project/subject/session identifier is valid.

        Identifiers can only contain alphanumeric characters and underscores.
        """
        for c in identifier:
            if c not in string.letters + string.digits + '_':
                return False
        return True

    def quit(self):
        self.app.quit_dialog.show()
        if self.app.quit_dialog.exec_():
            self.app.quit()
        return

    def upload(self):
        self.app.projects = {}
        for (patient_id, widgets) in self.project_widgets.iteritems():
            self.app.projects[patient_id] = str(widgets['edit'].text())
        self.app.subjects = {}
        for (patient_id, widgets) in self.subject_widgets.iteritems():
            self.app.subjects[patient_id] = str(widgets['edit'].text())
        self.app.sessions = {}
        for session_dict in self.session_widgets.itervalues():
            for (study_instance_uid, widgets) in session_dict.iteritems():
                session_id = str(widgets['edit'].text())
                self.app.sessions[study_instance_uid] = session_id
        self.app.upload()
        return

class LoginDialog(QtGui.QDialog):

    def __init__(self, app):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/login_dialog.ui', self)
        self.authenticate_button.setEnabled(False)
        self.app = app
        self.jsessionid = None
        return

    def edit_made(self, val):
        if self.login_edit.text() and self.password_edit.text():
            self.authenticate_button.setEnabled(True)
        else:
            self.authenticate_button.setEnabled(False)
        return

    def authenticate(self):
        # TODO real authentication
        self.info_label.setText('Authenticating...')
        # this will allow the label to update
        self.app.processEvents()
        try:
            self.app.xnat = XNAT(self.app.server_conf['xnat_base'], 
                                 self.login_edit.text(), 
                                 self.password_edit.text())
        except ValueError:
            self.info_label.setText('Authentication failed')
            return
        self.app.processEvents()
        self.info_label.setText('Getting server info (projects)...')
        self.app.processEvents()
        self.app.xnat.projects()
        self.app.processEvents()
        for project in self.app.xnat.user_projects():
            self.info_label.setText('Getting server info (%s)...' % project)
            self.app.processEvents()
            self.app.xnat.subjects(project)
            self.app.processEvents()
            self.app.xnat.sessions(project)
        self.app.get_upload_info()
        return

    def quit(self):
        self.app.quit_dialog.show()
        if self.app.quit_dialog.exec_():
            self.app.quit()
        return

class ExitNoticeDialog(QtGui.QDialog):

    def __init__(self, app, msg):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/exit_notice_dialog.ui', self)
        self.label.setText(msg)
        self.app = app
        return

class QuitDialog(QtGui.QDialog):

    def __init__(self, app):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/quit_dialog.ui', self)
        self.setModal(True)
        self.app = app
        return

class FileLoaderDialog(QtGui.QDialog):

    def __init__(self, app, paths):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/file_loader_dialog.ui', self)
        self.app = app
        self.paths = paths
        self.status_label.setText('Scanning for files...')
        self.progress.setRange(0, 1)
        self.progress.setValue(0)
        self.files = []
        self.quit_called = False
        return

    def scan(self):
        for path in self.paths:
            if os.path.isdir(path):
                for (dirpath, dirnames, fnames) in os.walk(path):
                    for f in fnames:
                        if f == 'DICOMDIR':
                            continue
                        self.files.append('%s/%s' % (dirpath, f))
            else:
                self.files.append(path)
        return

    def read(self):
        # dicom_files[PatientID][StudyInstanceUID] -> list of file names
        dicom_files = {}
        # studies[StudyInstanceUID] -> (study date, study time)
        studies = {}
        self.progress.setMaximum(len(self.files))
        for (i, fname) in enumerate(self.files):
            msg = 'Scanning files (%d of %d)...' % (i+1, len(self.files))
            self.status_label.setText(msg)
            self.progress.setValue(i+1)
            try:
                do = read_dicom_file(fname)
                patient_files = dicom_files.setdefault(do.PatientID, {})
                patient_files.setdefault(do.StudyInstanceUID, []).append(fname)
                if do.StudyInstanceUID not in studies:
                    t = (do.StudyDate, do.StudyTime)
                    studies[do.StudyInstanceUID] = t
            except:
                pass
            self.app.processEvents()
            if self.quit_called:
                return
        self.app.dicom_files = dicom_files
        self.app.studies = studies
        return

    def quit(self):
        self.app.quit_dialog.show()
        if self.app.quit_dialog.exec_():
            self.quit_called = True
        return

class AgreementDialog(QtGui.QDialog):

    def __init__(self, app):
        QtGui.QDialog.__init__(self)
        uic.loadUi('ui/agreement_dialog.ui', self)
        self.continue_button.setEnabled(False)
        self.app = app
        return

    def quit(self):
        self.app.quit_dialog.show()
        if self.app.quit_dialog.exec_():
            self.app.quit()
        return

    def set_agreement(self, value):
        self.continue_button.setEnabled(value)
        return

    def cont(self):
        self.app.login()
        return

app = Application(sys.argv, have_storescu)
app.setApplicationName('INCF One Click Upload')

if app.pre_quit:
    sys.exit(0)

sys.exit(app.exec_())

# eof
